package com.nico.podium.controller;
import com.nico.podium.domain.PodiumModels.*; import com.nico.podium.service.*; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import java.time.LocalDate; import java.util.List; import java.util.Map;
@RestController @RequestMapping("/api/track-days") public class TrackDayController extends ControllerSupport {
 private final TrackDayService days; private final SessionService sessions; public TrackDayController(AuthService auth,TrackDayService days,SessionService sessions){super(auth);this.days=days;this.sessions=sessions;}
 @GetMapping public List<TrackDay> list(@RequestParam(required=false)Long trackId,@RequestParam(required=false)Long vehicleId,@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to,@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-User-Id",required=false)String h){return days.list(userId(a,h),trackId,vehicleId,from,to);}
 @GetMapping("/stats") public List<TrackDayStats> stats(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-User-Id",required=false)String h){return days.stats(userId(a,h));}
 @PostMapping public TrackDay create(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-User-Id",required=false)String h,@RequestBody Map<String,Object>b){return days.create(userId(a,h),b);}
 @PostMapping("/complete") public CompletedTrackDay complete(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-User-Id",required=false)String h,@RequestBody Map<String,Object>b){return days.complete(userId(a,h),b);}
 @GetMapping("/{id:\\d+}") public Map<String,Object> get(@PathVariable Long id,@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-User-Id",required=false)String h){Long u=userId(a,h);return Map.of("trackDay",days.get(u,id),"sessions",sessions.list(u,id));}
 @PatchMapping("/{id:\\d+}") public TrackDay update(@PathVariable Long id,@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-User-Id",required=false)String h,@RequestBody Map<String,Object>b){return days.update(userId(a,h),id,b);}
 @DeleteMapping("/{id:\\d+}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(@PathVariable Long id,@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-User-Id",required=false)String h){days.delete(userId(a,h),id);}
 @GetMapping("/{id:\\d+}/sessions") public List<Session> listSessions(@PathVariable Long id,@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-User-Id",required=false)String h){return sessions.list(userId(a,h),id);}
 @PostMapping("/{id:\\d+}/sessions") public Session createSession(@PathVariable Long id,@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-User-Id",required=false)String h,@RequestBody Map<String,Object>b){return sessions.create(userId(a,h),id,b);}
}