package com.nico.podium.service.impl;
 import com.nico.podium.domain.PodiumModels.*; import com.nico.podium.repository.*; import com.nico.podium.service.PersonalRecordService; import com.nico.podium.service.TrackDayService; import com.nico.podium.service.TrackService; import com.nico.podium.service.VehicleService; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDate; import java.util.*; import static com.nico.podium.service.impl.ServiceSupportImpl.*;
@Service public class TrackDayServiceImpl implements TrackDayService {
 private final TrackDayRepository days; private final TrackService tracks; private final VehicleService vehicles; private final SessionRepository sessions; private final LapRepository laps; private final PersonalRecordService records;
 public TrackDayServiceImpl(TrackDayRepository days,TrackService tracks,VehicleService vehicles){this(days,tracks,vehicles,null,null,null);}
 @Autowired public TrackDayServiceImpl(TrackDayRepository days,TrackService tracks,VehicleService vehicles,SessionRepository sessions,LapRepository laps,PersonalRecordService records){this.days=days;this.tracks=tracks;this.vehicles=vehicles;this.sessions=sessions;this.laps=laps;this.records=records;}
 public List<TrackDay> list(Long userId,Long trackId,Long vehicleId,LocalDate from,LocalDate to){return days.findByUserId(userId).stream().filter(d->trackId==null||d.trackId().equals(trackId)).filter(d->vehicleId==null||vehicleId.equals(d.vehicleId())).filter(d->from==null||!d.startDate().isBefore(from)).filter(d->to==null||!d.startDate().isAfter(to)).toList();}
 public List<TrackDayStats> stats(Long userId){return days.findByUserId(userId).stream().map(day->{List<Lap> dayLaps=sessions.findByTrackDayId(day.id()).stream().flatMap(session->laps.findBySessionId(session.id()).stream()).toList();Long fastest=dayLaps.stream().mapToLong(Lap::timeMillis).min().orElse(0L);Long average=dayLaps.isEmpty()?0L:Math.round(dayLaps.stream().mapToLong(Lap::timeMillis).average().orElse(0));return new TrackDayStats(day.id(),fastest,average);}).toList();}
 public TrackDay get(Long userId,Long id){TrackDay d=days.findById(id).orElseThrow(()->missing("track day"));if(!d.userId().equals(userId))throw missing("track day");return d;}
 public TrackDay create(Long userId,Map<String,Object>b){Long trackId=numberRequired(b,"trackId");tracks.get(userId,trackId);Long vehicleId=number(b,"vehicleId");if(vehicleId!=null)vehicles.get(userId,vehicleId);LocalDate start=date(b,"startDate",LocalDate.now());return days.save(new TrackDay(null,userId,trackId,vehicleId,start,date(b,"endDate",start),text(b,"notes",null),text(b,"conditions",null)));}
 @Transactional public CompletedTrackDay complete(Long userId,Map<String,Object>b){if(sessions==null||laps==null||records==null)throw error(org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR,"completion is unavailable");Long trackId=numberRequired(b,"trackId");tracks.get(userId,trackId);Long vehicleId=number(b,"vehicleId");if(vehicleId!=null)vehicles.get(userId,vehicleId);LocalDate start=date(b,"startDate",LocalDate.now());LocalDate end=date(b,"endDate",start);if(end.isBefore(start))throw error(org.springframework.http.HttpStatus.BAD_REQUEST,"endDate must be on or after startDate");TrackDay day=days.save(new TrackDay(null,userId,trackId,vehicleId,start,end,text(b,"notes",null),text(b,"conditions",null)));List<Session> savedSessions=new ArrayList<>();Map<Long,List<Lap>> savedLaps=new LinkedHashMap<>();for(Object rawSession:(List<?>)b.getOrDefault("sessions",List.of())){Map<String,Object> sessionBody=(Map<String,Object>)rawSession;Session session=sessions.save(new Session(null,day.id(),text(sessionBody,"name","Session"),text(sessionBody,"notes",null)));savedSessions.add(session);List<Lap> sessionLaps=new ArrayList<>();for(Object rawLap:(List<?>)sessionBody.getOrDefault("laps",List.of())){Map<String,Object> lapBody=(Map<String,Object>)rawLap;Long time=number(lapBody,"timeMillis");if(time==null||time<=0)throw error(org.springframework.http.HttpStatus.BAD_REQUEST,"timeMillis must be positive");Lap lap=laps.save(new Lap(null,session.id(),integer(lapBody,"lapNumber",sessionLaps.size()+1),time));records.refresh(userId,lap.id(),session.id(),time);sessionLaps.add(lap);}savedLaps.put(session.id(),sessionLaps);}return new CompletedTrackDay(day,savedSessions,savedLaps);}
 public TrackDay update(Long userId,Long id,Map<String,Object>b){TrackDay c=get(userId,id);Long trackId=number(b,"trackId")==null?c.trackId():number(b,"trackId");tracks.get(userId,trackId);Long vehicleId=number(b,"vehicleId")==null?c.vehicleId():number(b,"vehicleId");if(vehicleId!=null)vehicles.get(userId,vehicleId);return days.save(new TrackDay(c.id(),c.userId(),trackId,vehicleId,date(b,"startDate",c.startDate()),date(b,"endDate",c.endDate()),text(b,"notes",c.notes()),text(b,"conditions",c.conditions())));}
 public void delete(Long userId,Long id){get(userId,id);days.deleteById(id);}
}