package com.nico.podium.service.Impl;
import com.nico.podium.domain.PodiumModels.TrackDay; import com.nico.podium.repository.TrackDayRepository; import com.nico.podium.service.TrackDayService; import com.nico.podium.service.TrackService; import com.nico.podium.service.VehicleService; import org.springframework.stereotype.Service; import java.time.LocalDate; import java.util.List; import java.util.Map; import static com.nico.podium.service.Impl.ServiceSupportImpl.*;
@Service public class TrackDayServiceImpl implements TrackDayService {
 private final TrackDayRepository days; private final TrackService tracks; private final VehicleService vehicles;
 public TrackDayServiceImpl(TrackDayRepository days,TrackService tracks,VehicleService vehicles){this.days=days;this.tracks=tracks;this.vehicles=vehicles;}
 public List<TrackDay> list(String userId,String trackId,String vehicleId,LocalDate from,LocalDate to){return days.findByUserId(userId).stream().filter(d->trackId==null||d.trackId().equals(trackId)).filter(d->vehicleId==null||vehicleId.equals(d.vehicleId())).filter(d->from==null||!d.date().isBefore(from)).filter(d->to==null||!d.date().isAfter(to)).toList();}
 public TrackDay get(String userId,String id){TrackDay d=days.findById(id).orElseThrow(()->missing("track day"));if(!d.userId().equals(userId))throw missing("track day");return d;}
 public TrackDay create(String userId,Map<String,Object>b){String trackId=required(b,"trackId");tracks.get(userId,trackId);String vehicleId=text(b,"vehicleId",null);if(vehicleId!=null)vehicles.get(userId,vehicleId);return days.save(new TrackDay(id(),userId,trackId,vehicleId,date(b,"date",LocalDate.now()),text(b,"notes",null),text(b,"conditions",null)));}
 public TrackDay update(String userId,String id,Map<String,Object>b){TrackDay c=get(userId,id);String trackId=text(b,"trackId",c.trackId());tracks.get(userId,trackId);String vehicleId=text(b,"vehicleId",c.vehicleId());if(vehicleId!=null)vehicles.get(userId,vehicleId);return days.save(new TrackDay(c.id(),c.userId(),trackId,vehicleId,date(b,"date",c.date()),text(b,"notes",c.notes()),text(b,"conditions",c.conditions())));}
 public void delete(String userId,String id){get(userId,id);days.deleteById(id);}
}