package com.nico.podium.service.impl;
 import com.nico.podium.domain.PodiumModels.TrackDay; import com.nico.podium.repository.TrackDayRepository; import com.nico.podium.service.TrackDayService; import com.nico.podium.service.TrackService; import com.nico.podium.service.VehicleService; import org.springframework.stereotype.Service; import java.time.LocalDate; import java.util.List; import java.util.Map; import static com.nico.podium.service.impl.ServiceSupportImpl.*;
@Service public class TrackDayServiceImpl implements TrackDayService {
 private final TrackDayRepository days; private final TrackService tracks; private final VehicleService vehicles;
 public TrackDayServiceImpl(TrackDayRepository days,TrackService tracks,VehicleService vehicles){this.days=days;this.tracks=tracks;this.vehicles=vehicles;}
 public List<TrackDay> list(Long userId,Long trackId,Long vehicleId,LocalDate from,LocalDate to){return days.findByUserId(userId).stream().filter(d->trackId==null||d.trackId().equals(trackId)).filter(d->vehicleId==null||vehicleId.equals(d.vehicleId())).filter(d->from==null||!d.date().isBefore(from)).filter(d->to==null||!d.date().isAfter(to)).toList();}
 public TrackDay get(Long userId,Long id){TrackDay d=days.findById(id).orElseThrow(()->missing("track day"));if(!d.userId().equals(userId))throw missing("track day");return d;}
 public TrackDay create(Long userId,Map<String,Object>b){Long trackId=numberRequired(b,"trackId");tracks.get(userId,trackId);Long vehicleId=number(b,"vehicleId");if(vehicleId!=null)vehicles.get(userId,vehicleId);return days.save(new TrackDay(null,userId,trackId,vehicleId,date(b,"date",LocalDate.now()),text(b,"notes",null),text(b,"conditions",null)));}
 public TrackDay update(Long userId,Long id,Map<String,Object>b){TrackDay c=get(userId,id);Long trackId=number(b,"trackId")==null?c.trackId():number(b,"trackId");tracks.get(userId,trackId);Long vehicleId=number(b,"vehicleId")==null?c.vehicleId():number(b,"vehicleId");if(vehicleId!=null)vehicles.get(userId,vehicleId);return days.save(new TrackDay(c.id(),c.userId(),trackId,vehicleId,date(b,"date",c.date()),text(b,"notes",c.notes()),text(b,"conditions",c.conditions())));}
 public void delete(Long userId,Long id){get(userId,id);days.deleteById(id);}
}